name: gg_git
description: A collection of git helper scripts for repository checks and other utilities.
version: 1.0.1
repository: https://github.com/inlavigo/gg_git.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_args: ^1.0.3
  gg_console_colors: ^1.0.0
  gg_process: ^1.0.6
  meta: ^1.12.0
  mocktail: ^1.0.3
  path: ^1.8.0

dev_dependencies:
  gg_capture_print: ^1.0.2
  gg_check: ^1.0.2
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
  recase: ^4.1.0
