name: gg_git
description: A collection of git helper scripts for repository checks and other utilities.
version: 2.5.1
repository: https://github.com/inlavigo/gg_git.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^1.1.0
  gg_console_colors: ^2.0.0
  gg_is_github: ^1.0.1
  gg_log: ^1.0.0
  gg_process: ^1.0.7
  gg_status_printer: ^1.0.7
  meta: ^1.12.0
  mocktail: ^1.0.3
  path: ^1.8.0

dev_dependencies:
  gg_capture_print: ^1.0.3
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
  recase: ^4.1.0
  gg_install_gg: ^1.0.1